spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/question-box
    username: question-box
    password: password
    initialization-mode: ALWAYS
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# The following is standard Spring Security OAuth2 configuration.
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          # Replace with the domain of your Auth0 tenant.
          # Note the trailing slash is important!
          issuer-uri: https://questionboxclone.jp.auth0.com/

auth0:
  # Replace with the API Identifier for your Auth0 API.
  audience: http://question-clone-box.example.com
